name: mzadqatar_car_deals
description: "Car deal analyzer for mzadqatar.com"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
